import type { Metadata } from 'next'
import { Crete_Round, Work_Sans, Roboto } from 'next/font/google'
import './globals.css'
import Navbar from './(root)/_components/navbar'
import Footer from './(root)/_components/footer'
import { ChildrenProps } from '@/types'
const creteRound = Crete_Round({
	weight: ['400'],
	variable: '--font-creteRound',
	subsets: ['latin'],
})

const workSans = Work_Sans({
	weight: ['500', '600'],
	variable: '--font-workSans',
	subsets: ['latin'],
})
const roboto = Roboto({
	subsets: ['latin'],
	weight: ['400', '500', '700'],
	variable: '--font-roboto',
})

export const metadata: Metadata = {
	title: 'Sifatdev',
	description: 'Generated by create next app',
	icons: {
		icon: '/assets/logo.png',
	},
}

export default async function RootLayout({ children }: ChildrenProps) {
	return (
		<html lang='en' suppressHydrationWarning>
			<body
				className={`${creteRound.variable} ${workSans.variable}${roboto.className} antialiased`}
				suppressHydrationWarning
			>
				<div className='overflow-x-hidden w-screen overflow-y-hidden custom-scrollbar'>
					<Navbar />
					<main className='overflow-x-hidden'>{children}</main>
					<Footer />
				</div>
			</body>
		</html>
	)
}
